Chaos:
  StateOfChaos:
    settings-key: NeoGasDistributor-StateOfChaos
Cqrs:
  RabbitConnectionString:
    settings-key: CqrsRabbitConnString
    types:
      - RabbitMq
  RetryDelay:
    settings-key: NeoGasDistributor-CqrsRetryDelay
MatchingEngineClient:
  Host:
    settings-key: MatchingEngine-Host
  Port:
    settings-key: MatchingEngine-Port
NeoGasDistributor:
  CreateDistributionPlanCron:
    settings-key: NeoGasDistributor-CreateDistributionPlanCron
  CreateDistributionPlanDelay:
    settings-key: NeoGasDistributor-CreateDistributionPlanDelay
  CreateBalanceSnapshotCron:
    settings-key: NeoGasDistributor-CreateBalanceSnapshotCron
  CreateBalanceSnapshotDelay:
    settings-key: NeoGasDistributor-CreateBalanceSnapshotDelay
  GasAssetId:
    settings-key: NeoGasDistributor-GasAssetId
  NeoAssetId:
    settings-key: NeoGasDistributor-NeoAssetId
  Db:
    DataConnString:
      settings-key: NeoGasDistributor-DataConnString
      types:
        - AzureTableStorage
    HangfireConnString:
      settings-key: HangfireConnString
    HangfireDatabase:
      settings-key: NeoGasDistributor-HangfireDatabase
    LogsConnString:
      settings-key: NeoGasDistributor-LogsConnString
      types:
        - AzureTableStorage
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    QueueName:
      settings-key: SlackQueueName
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl